name: "Archive Website via Python Script"
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        required: true
  repository_dispatch:
    types: [archive_site_python]

jobs:
  archive_python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 waybackpy

      - name: Determine archive URL
        id: archive_url
        run: |
          if [ -n "${{ github.event.inputs.url }}" ]; then
            echo "url=${{ github.event.inputs.url }}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ github.event.client_payload.url }}" ]; then
            echo "url=${{ github.event.client_payload.url }}" >> "$GITHUB_OUTPUT"
          else
            echo "No URL provided for archiving." >&2
            exit 1
          fi

      - name: Set up git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Run archive script
        env:
          ARCHIVE_USER_AGENT: "Mozilla/5.0 (compatible; WhiteHouseArchiveBot/1.0; +https://github.com/alphaO4/WhiteHouse-Archive)"
        run: |
          python scripts/archive_site.py --url "${{ steps.archive_url.outputs.url }}"

      - name: Commit archived pages
        run: |
          git add archived
          if ! git diff --quiet --cached; then
            git commit -m "Archived ${{ github.event.inputs.url }} and its sub-links"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
